"""deletions in user model

Revision ID: 3663dc6cac59
Revises: a65c2373962e
Create Date: 2024-07-28 20:00:29.733272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3663dc6cac59'
down_revision = 'a65c2373962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
